### ISSUE TITLE
How do I provide the travis public key?

### ISSUE THREAD

**Issue by rossdargan** [vangie/travis-ci-webhook#2]
I'm providing the following environmental variable:

   - TRAVIS_PUBKEY:-----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvtjdLkS+FP+0fPC09j25 y/PiuYDDivIT86COVedvlElk99BBYTrqNaJybxjXbIZ1Q6xFNhOY+iTcBr4E1zJu tizF3Xi0V9tOuP/M8Wn4Y/1lCWbQKlWrNQuqNBmhovF4K3mDCYswVbpgTmp+JQYu Bm9QMdieZMNry5s6aiMA9aSjDlNyedvSENYo18F+NYg1J0C0JiPYTxheCb4optr1 5xNzFKhAkuGs4XTOA5C7Q06GCKtDNf44s/CVE30KODUxBi0MCKaxiXw/yy55zxX2 /YdGphIyQiA5iO1986ZmZCLLW8udz9uhW5jUr3Jlp9LbmphAC61bVSf4ou2YsJaN 0QIDAQAB -----END PUBLIC KEY-----

But I'm still getting the following error:

TypeError: must provide a 'public_key' option
    at create (/usr/src/app/node_modules/travisci-webhook-handler/handler.js:22:15)
    at Object.<anonymous> (/usr/src/app/index.js:19:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)

Any help would be great :)

Ta

Ross

**Comment by vangie** [comment]
Add following content to file `env.override`
```
TRAVIS_PUBKEY="-----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvtjdLkS+FP+0fPC09j25 y/PiuYDDivIT86COVedvlElk99BBYTrqNaJybxjXbIZ1Q6xFNhOY+iTcBr4E1zJu tizF3Xi0V9tOuP/M8Wn4Y/1lCWbQKlWrNQuqNBmhovF4K3mDCYswVbpgTmp+JQYu Bm9QMdieZMNry5s6aiMA9aSjDlNyedvSENYo18F+NYg1J0C0JiPYTxheCb4optr1 5xNzFKhAkuGs4XTOA5C7Q06GCKtDNf44s/CVE30KODUxBi0MCKaxiXw/yy55zxX2 /YdGphIyQiA5iO1986ZmZCLLW8udz9uhW5jUr3Jlp9LbmphAC61bVSf4ou2YsJaN 0QIDAQAB -----END PUBLIC KEY-----"
```
and
```sh
docker run -d \
  -p 7777:7777 \
  -v ${PWD}/scripts:/usr/src/app/scripts \
  -v env.override:/usr/src/app/.env.override \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --name travis-ci-webhook \
  vangie/travis-ci-webhook
```

**Comment by rossdargan** [comment]
Thanks :) I do have another issue now, but I'll close this one!
